---
definitions:
  config:
    /hippo:namespaces/website/parameters:
      /editor:templates:
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties:
          - mode
          frontend:references:
          - wicket.model
          - model.compareTo
          - engine
          - validator.id
          frontend:services:
          - wicket.id
          - validator.id
          /root:
            extension.left: ${cluster.id}.left
            extension.right: ${cluster.id}.right
            jcr:primaryType: frontend:plugin
            plugin.class: org.hippoecm.frontend.editor.layout.TwoColumn
            wicket.extensions:
            - extension.left
            - extension.right
          /left:
            item: ${cluster.id}.left.item
            jcr:primaryType: frontend:plugin
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.left
          /right:
            item: ${cluster.id}.right.item
            jcr:primaryType: frontend:plugin
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.right
          /name:
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
            caption: Name
            field: name
            hint: ''
            jcr:primaryType: frontend:plugin
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
          /parametertype:
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              orientation: vertical
              source: /content/documents/administration/website/parameter-type
            caption: Parameter type
            field: parametertype
            hint: ''
            jcr:primaryType: frontend:plugin
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
          /ismandatory:
            /cluster.options:
              falseLabel: 'No'
              jcr:primaryType: frontend:pluginconfig
              trueLabel: 'Yes'
            caption: Is Mandatory
            field: ismandatory
            jcr:primaryType: frontend:plugin
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
          /path:
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
            caption: Parameter path
            field: path
            hint: ''
            jcr:primaryType: frontend:plugin
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
          /description:
            /cluster.options:
              ckeditor.config.appended.json: '{toolbar: [{ name: ''summarytoolbar'',  items:
                [''Link'',''PickInternalLink'',''Source''] }] }'
              jcr:primaryType: frontend:pluginconfig
            caption: Description
            field: description
            hint: ''
            jcr:primaryType: frontend:plugin
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
        jcr:primaryType: editor:templateset
      /hipposysedit:nodetype:
        /hipposysedit:nodetype:
          /description:
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: website:description
            hipposysedit:primary: false
            hipposysedit:type: hippostd:html
            jcr:primaryType: hipposysedit:field
          /ismandatory:
            hipposysedit:mandatory: true
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: website:ismandatory
            hipposysedit:primary: false
            hipposysedit:type: selection:BooleanRadioGroup
            hipposysedit:validators:
            - required
            jcr:primaryType: hipposysedit:field
          /name:
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: website:name
            hipposysedit:primary: false
            hipposysedit:type: String
            jcr:primaryType: hipposysedit:field
          /parametertype:
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: website:parametertype
            hipposysedit:primary: false
            hipposysedit:type: DynamicDropdown
            jcr:primaryType: hipposysedit:field
          /path:
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: website:path
            hipposysedit:primary: false
            hipposysedit:type: String
            jcr:primaryType: hipposysedit:field
          hipposysedit:node: true
          hipposysedit:supertype:
          - hippo:compound
          - hippostd:relaxed
          hipposysedit:uri: http://digital.nhs.uk/jcr/website/nt/1.0
          jcr:mixinTypes:
          - mix:referenceable
          - hipposysedit:remodel
          jcr:primaryType: hipposysedit:nodetype
        jcr:mixinTypes:
        - mix:referenceable
        jcr:primaryType: hippo:handle
      /hipposysedit:prototypes:
        /hipposysedit:prototype:
          jcr:primaryType: website:parameters
          website:ismandatory: false
          website:title: ''
        jcr:primaryType: hipposysedit:prototypeset
      jcr:mixinTypes:
      - editor:editable
      - mix:referenceable
      jcr:primaryType: hipposysedit:templatetype
