---
definitions:
  config:
    /hippo:namespaces/website/transportroutes:
      /editor:templates:
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties:
          - mode
          frontend:references:
          - wicket.model
          - model.compareTo
          - engine
          - validator.id
          frontend:services:
          - wicket.id
          - validator.id
          /root:
            item: ${cluster.id}.field
            jcr:primaryType: frontend:plugin
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /routenumber:
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
            caption: Route number
            field: routenumber
            jcr:primaryType: frontend:plugin
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
          /routelink:
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
            caption: Links
            compoundList: website:externallink
            contentPickerType: links
            field: routelink
            hint: ''
            jcr:primaryType: frontend:plugin
            plugin.class: org.onehippo.forge.contentblocks.ContentBlocksFieldPlugin
            wicket.id: ${cluster.id}.field
        jcr:primaryType: editor:templateset
      /hipposysedit:nodetype:
        /hipposysedit:nodetype:
          /routelink:
            hipposysedit:multiple: false
            hipposysedit:ordered: true
            hipposysedit:path: website:routelink
            hipposysedit:type: hippo:compound
            hipposysedit:validators:
            - contentblocks-validator
            jcr:primaryType: hipposysedit:field
          /routenumber:
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: website:routenumber
            hipposysedit:primary: false
            hipposysedit:type: String
            jcr:primaryType: hipposysedit:field
          hipposysedit:node: true
          hipposysedit:supertype:
          - hippo:compound
          - hippostd:relaxed
          hipposysedit:uri: http://digital.nhs.uk/jcr/website/nt/1.0
          jcr:mixinTypes:
          - mix:referenceable
          - hipposysedit:remodel
          jcr:primaryType: hipposysedit:nodetype
        jcr:mixinTypes:
        - mix:referenceable
        jcr:primaryType: hippo:handle
      /hipposysedit:prototypes:
        /hipposysedit:prototype:
          jcr:primaryType: website:transportroutes
          website:version: ''
        jcr:primaryType: hipposysedit:prototypeset
      jcr:mixinTypes:
      - editor:editable
      - mix:referenceable
      jcr:primaryType: hipposysedit:templatetype
