---
##
# AWS Code Build spec for building and deploying Hippo CMS
#

version: 0.1

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -qqy software-properties-common python-software-properties
      - apt-get install -qqy build-essential git awscli curl python-pip python-dev
      - pip install virtualenv

      # remove oracle java
      - update-alternatives --remove "java" "/usr/lib/jvm/java-8-oracle/jre/bin/java"
      - rm -r /usr/lib/jvm/java-8-oracle

      # Java 8 install
      - apt-get update
      - apt-get install -y openjdk-8-jdk
      - apt-get install -y maven
      - mvn --verison

      - update-alternatives --config java
      - java -version

      # SSH key
      - aws s3 cp s3://config.mgt.nhsd.io/codebuild/hippo_build/nhs-ci_rsa $HOME/.ssh/nhs-ci_rsa
      - aws s3 cp s3://config.mgt.nhsd.io/codebuild/hippo_build/nhs-ci_rsa.pub $HOME/.ssh/nhs-ci_rsa.pub
      - chmod 600 $HOME/.ssh/nhs-ci_rsa

      # Rundeck credentials
      - aws s3 cp s3://config.mgt.nhsd.io/codebuild/hippo_build/rd.password $HOME/rd.password

      # Add static.hosting.onehippo.com and github.com as known host
      - touch $HOME/.ssh/known_hosts
      - ssh-keygen -R static.hosting.onehippo.com
      - ssh-keyscan static.hosting.onehippo.com >> $HOME/.ssh/known_hosts
      - ssh-keygen -R github.com
      - ssh-keyscan github.com >> $HOME/.ssh/known_hosts

      # Print the Ubuntu version
      - cat /etc/lsb-release

  build:
    commands:
      # Tag
      - ssh-agent bash -c "
        ssh-add $HOME/.ssh/nhs-ci_rsa && cd ci-cd &&
        make version.bumpup"
      # Build
      - cd ci-cd && make clean build
      # Set git commit status
      - cd ci-cd && make github.status.success
      # Upload tgz files to various destinations
      - ssh-agent bash -c "
        ssh-add $HOME/.ssh/nhs-ci_rsa &&
        cd ci-cd && make ondemand.upload"
      # Deploy to Test Environment
      - . $HOME/rd.password && cd ci-cd && make ondemand.deploy
      # Push tag back to github
      - ssh-agent bash -c "
        ssh-add $HOME/.ssh/nhs-ci_rsa && cd ci-cd &&
        make git.update-environment-tag &&
        git push --tags"

artifacts:
  files:
    - "**/*"

cache:
  paths:
    - '/root/.m2/**/*'
