---
##
# AWS Code Build spec for scheduling next production release
#

version: 0.1

phases:
  install:
    commands:
      # SSH key
      - aws s3 cp s3://config.mgt.nhsd.io/codebuild/hippo_build/nhs-ci_rsa $HOME/.ssh/nhs-ci_rsa
      - aws s3 cp s3://config.mgt.nhsd.io/codebuild/hippo_build/nhs-ci_rsa.pub $HOME/.ssh/nhs-ci_rsa.pub
      - chmod 600 $HOME/.ssh/nhs-ci_rsa

      # Rundeck credentials
      - aws s3 cp s3://config.mgt.nhsd.io/codebuild/hippo_build/rd.password $HOME/rd.password

      # Add github.com as known host
      - touch $HOME/.ssh/known_hosts
      - ssh-keygen -R github.com
      - ssh-keyscan github.com >> $HOME/.ssh/known_hosts

      # remove `https` origin and add `git@` so we cna use SSH keys to authenticate
      - git remote remove origin
      - git remote add origin git@github.com:NHS-digital-website/hippo.git

  build:
    commands:
      - ssh-agent bash -c "
        ssh-add $HOME/.ssh/nhs-ci_rsa && cd ci-cd &&
        make git.update-environment-tag ENV=prd VERSION=rc &&
        make git.update-environment-tag ENV=rc VERSION=uat"
      - . $HOME/rd.password && cd ci-cd && make ondemand.schedule-deploy ENV=prd
      - make notify.slack

artifacts:
  files:
    - "**/*"
