package uk.nhs.digital.highlighter;

public enum Language {

    ACCESSLOG("accesslog", "Access log"),
    ACTIONSCRIPT("actionscript", "ActionScript"),
    ADA("ada", "Ada"),
    ANGELSCRIPT("angelscript", "AngelScript"),
    APACHE("apache", "Apache"),
    APPLESCRIPT("applescript", "AppleScript"),
    ARDUINO("arduino", "Arduino"),
    ARMASM("armasm", "ARM Assembly"),
    ASCIIDOC("asciidoc", "AsciiDoc"),
    ASPECTJ("aspectj", "AspectJ"),
    AUTOHOTKEY("autohotkey", "AutoHotkey"),
    AUTOIT("autoit", "AutoIt"),
    AVRASM("avrasm", "AVR Assembler"),
    AWK("awk", "Awk"),
    AXAPTA("axapta", "Axapta"),
    BASH("bash", "Bash"),
    BASIC("basic", "Basic"),
    BNF("bnf", "Backus–Naur Form"),
    CAL("cal", "C/AL"),
    CAPNPROTO("capnproto", "Cap’n Proto"),
    CEYLON("ceylon", "Ceylon"),
    CLEAN("clean", "Clean"),
    CLOJURE("clojure", "Clojure"),
    CLOJUREREPL("clojure-repl", "Clojure REPL"),
    CMAKE("cmake", "CMake"),
    COFFEESCRIPT("coffeescript", "CoffeeScript"),
    COQ("coq", "Coq"),
    COS("cos", "Caché Object Script"),
    CPP("cpp", "C++"),
    CRMSH("crmsh", "crmsh"),
    CRYSTAL("crystal", "Crystal"),
    CS("cs", "C#"),
    CSP("csp", "CSP"),
    CSS("css", "CSS"),
    D("d", "D"),
    DART("dart", "Dart"),
    DELPHI("delphi", "Delphi"),
    DIFF("diff", "Diff"),
    DJANGO("django", "Django"),
    DNS("dns", "DNS Zone file"),
    DOCKERFILE("dockerfile", "Dockerfile"),
    DOS("dos", "DOS .bat"),
    DSCONFIG("dsconfig", "dsconfig"),
    DTS("dts", "Device Tree"),
    DUST("dust", "Dust"),
    ELIXIR("elixir", "Elixir"),
    ELM("elm", "Elm"),
    ERB("erb", "ERB (Embedded Ruby)"),
    ERLANG("erlang", "Erlang"),
    ERLANGREPL("erlang-repl", "Erlang REPL"),
    EXCEL("excel", "Excel"),
    FIX("fix", "FIX"),
    FLIX("flix", "Flix"),
    FORTRAN("fortran", "Fortran"),
    FSHARP("fsharp", "F#"),
    GAMS("gams", "GAMS"),
    GAUSS("gauss", "GAUSS"),
    GCODE("gcode", "G-code (ISO 6983)"),
    GHERKIN("gherkin", "Gherkin"),
    GLSL("glsl", "GLSL"),
    GML("gml", "GML"),
    GO("go", "Go"),
    GOLO("golo", "Golo"),
    GRADLE("gradle", "Gradle"),
    GROOVY("groovy", "Groovy"),
    HAML("haml", "Haml"),
    HANDLEBARS("handlebars", "Handlebars"),
    HASKELL("haskell", "Haskell"),
    HAXE("haxe", "Haxe"),
    HSP("hsp", "HSP"),
    HTML("xml", "HTML"),
    HTTP("http", "HTTP"),
    HY("hy", "Hy"),
    INI("ini", "Ini, TOML"),
    IRPF90("irpf90", "IRPF90"),
    ISBL("isbl", "ISBL"),
    JAVA("java", "Java"),
    JAVASCRIPT("javascript", "JavaScript"),
    JBOSSCLI("jboss-cli", "jboss-cli"),
    JSON("json", "JSON"),
    JULIA("julia", "Julia"),
    KOTLIN("kotlin", "Kotlin"),
    KQL("q", "KQL"),
    LASSO("lasso", "Lasso"),
    LDIF("ldif", "LDIF"),
    LEAF("leaf", "Leaf"),
    LESS("less", "Less"),
    LISP("lisp", "Lisp"),
    LIVECODESERVER("livecodeserver", "LiveCode"),
    LIVESCRIPT("livescript", "LiveScript"),
    LLVM("llvm", "LLVM IR"),
    LSL("lsl", "Linden Scripting Language"),
    LUA("lua", "Lua"),
    MAKEFILE("makefile", "Makefile"),
    MARKDOWN("markdown", "Markdown"),
    MATHEMATICA("mathematica", "Mathematica"),
    MATLAB("matlab", "Matlab"),
    MAXIMA("maxima", "Maxima"),
    MEL("mel", "MEL"),
    MERCURY("mercury", "Mercury"),
    MIPSASM("mipsasm", "MIPS Assembly"),
    MIZAR("mizar", "Mizar"),
    MOJOLICIOUS("mojolicious", "Mojolicious"),
    MONKEY("monkey", "Monkey"),
    MOONSCRIPT("moonscript", "MoonScript"),
    N1QL("n1ql", "N1QL"),
    NGINX("nginx", "Nginx"),
    NIMROD("nimrod", "Nimrod"),
    NIX("nix", "Nix"),
    NSIS("nsis", "NSIS"),
    OBJECTIVEC("objectivec", "Objective-C"),
    OCAML("ocaml", "OCaml"),
    OPENSCAD("openscad", "OpenSCAD"),
    OXYGENE("oxygene", "Oxygene"),
    PARSER3("parser3", "Parser3"),
    PERL("perl", "Perl"),
    PF("pf", "pf"),
    PGSQL("pgsql", "PostgreSQL SQL dialect and PL/pgSQL"),
    PHP("php", "PHP"),
    PLAINTEXT("plaintext", "plaintext"),
    PONY("pony", "Pony"),
    POWERSHELL("powershell", "PowerShell"),
    PROCESSING("processing", "Processing"),
    PROFILE("profile", "Python profile"),
    PROLOG("prolog", "Prolog"),
    PROPERTIES("properties", "Properties"),
    PUPPET("puppet", "Puppet"),
    PUREBASIC("purebasic", "PureBASIC"),
    PYTHON("python", "Python"),
    Q("q", "Q"),
    QML("qml", "QML"),
    R("r", "R"),
    REASONML("reasonml", "ReasonML"),
    RIB("rib", "RenderMan RIB"),
    ROBOCONF("roboconf", "Roboconf"),
    RSL("rsl", "RenderMan RSL"),
    RUBY("ruby", "Ruby"),
    RULESLANGUAGE("ruleslanguage", "Oracle Rules Language"),
    RUST("rust", "Rust"),
    SAS("sas", "SAS"),
    SCALA("scala", "Scala"),
    SCHEME("scheme", "Scheme"),
    SCILAB("scilab", "Scilab"),
    SCSS("scss", "SCSS"),
    SHELL("shell", "Shell Session"),
    SMALI("smali", "Smali"),
    SMALLTALK("smalltalk", "Smalltalk"),
    SML("sml", "SML"),
    SQF("sqf", "SQF"),
    SQL("sql", "SQL"),
    STAN("stan", "Stan"),
    STATA("stata", "Stata"),
    STYLUS("stylus", "Stylus"),
    SUBUNIT("subunit", "SubUnit"),
    SWIFT("swift", "Swift"),
    TAGGERSCRIPT("taggerscript", "Tagger Script"),
    TCL("tcl", "Tcl"),
    TEX("tex", "TeX"),
    THRIFT("thrift", "Thrift"),
    TP("tp", "TP"),
    TWIG("twig", "Twig"),
    TYPESCRIPT("typescript", "TypeScript"),
    VALA("vala", "Vala"),
    VBNET("vbnet", "VB.NET"),
    VBSCRIPT("vbscript", "VBScript"),
    VBSCRIPTHTML("vbscript-html", "VBScript in HTML"),
    VERILOG("verilog", "Verilog"),
    VHDL("vhdl", "VHDL"),
    VIM("vim", "Vim Script"),
    X86ASM("x86asm", "Intel x86 Assembly"),
    XL("xl", "XL"),
    XML("xml", "XML"),
    XQUERY("xquery", "XQuery"),
    YAML("yaml", "YAML"),
    ZEPHIR("zephir", "Zephir");

    private final String key;
    private final String label;

    Language(final String key, final String label) {
        this.key = key;
        this.label = label;
    }

    public String getKey() {
        return key;
    }

    public String getLabel() {
        return label;
    }

    public static Language getByKey(String name) {
        for (Language l : Language.values()) {
            if (l.getKey().replace("-", "").equalsIgnoreCase(name.replace("-", ""))) {
                return l;
            }
        }
        return null;
    }
}
