---
definitions:
  config:
    /hst:hst/hst:hosts/training:
      /io:
        /nhsd:
          /training:
            /content:
              .meta:residual-child-node-category: content
              jcr:primaryType: hst:virtualhost
            /hst:root:
              /gdpr:
                .meta:residual-child-node-category: content
                hst:ismapped: false
                hst:namedpipeline: TargetingRestApiPipeline
                hst:types:
                - rest
                jcr:primaryType: hst:mount
              hst:mountpoint: /hst:hst/hst:sites/common
              hst:responseheaders:
              - 'Strict-Transport-Security : max-age=31536000'
              - 'Content-Security-Policy: upgrade-insecure-requests'
              - 'Referrer-Policy: no-referrer-when-downgrade'
              - 'Feature-Policy: vibrate ''none''; microphone ''none''; camera ''none'';
                payment ''none''; accelerometer ''none''; ambient-light-sensor ''none'';
                magnetometer ''none''; midi ''none''; usb ''none''; wake-lock ''none'';
                execution-while-out-of-viewport ''none''; sync-xhr ''self''; gyroscope
                ''none''; push ''self''; speaker *;  fullscreen *'
              jcr:primaryType: hst:mount
            jcr:primaryType: hst:virtualhost
          jcr:primaryType: hst:virtualhost
        jcr:primaryType: hst:virtualhost
      hst:cmslocation: https://cms-training.nhsd.io
      jcr:primaryType: hst:virtualhostgroup
