---
definitions:
  config:
    /hst:hst/hst:hosts/training:
      /io:
        /nhsd:
          /training:
            /content:
              .meta:residual-child-node-category: content
              jcr:primaryType: hst:virtualhost
            /hst:root:
              /gdpr:
                .meta:residual-child-node-category: content
                hst:ismapped: false
                hst:namedpipeline: TargetingRestApiPipeline
                hst:types:
                - rest
                jcr:primaryType: hst:mount
              hst:mountpoint: /hst:hst/hst:sites/common
              jcr:primaryType: hst:mount
            jcr:primaryType: hst:virtualhost
          jcr:primaryType: hst:virtualhost
        jcr:primaryType: hst:virtualhost
      hst:cmslocation: https://cms-training.nhsd.io
      jcr:primaryType: hst:virtualhostgroup
