---
definitions:
  config:
    /hst:hst/hst:hosts:
      /localhost:
        /localhost:
          /hst:root:
            /api:
              .meta:residual-child-node-category: content
              hst:alias: api
              hst:ismapped: false
              hst:namedpipeline: RestApiPipeline
              hst:types:
              - rest
              jcr:primaryType: hst:mount
            hst:contextpath: ''
            hst:homepage: root
            hst:mountpoint: /hst:hst/hst:sites/common
            jcr:primaryType: hst:mount
          jcr:primaryType: hst:virtualhost
        hst:cmslocation: http://localhost:8080/cms
        hst:defaultport: 8080
        jcr:primaryType: hst:virtualhostgroup
      hst:defaultcontextpath: ''
      hst:diagnosticsenabled: false
      hst:scheme: http
    /hst:hst/hst:hosts/dev:
      hst:cmslocation: http://cms-dev.nhsd.io:8080/cms
      hst:defaultport: 8080
    /hst:hst/hst:hosts/prd:
      hst:cmslocation: http://cms.digital.nhs.uk:8080/cms
      hst:defaultport: 8080
    /hst:hst/hst:hosts/training:
      hst:cmslocation: http://cms-training.nhsd.io:8080/cms
      hst:defaultport: 8080
    /hst:hst/hst:hosts/tst:
      hst:cmslocation: http://cms-tst.nhsd.io:8080/cms
      hst:defaultport: 8080
    /hst:hst/hst:hosts/uat:
      hst:cmslocation: http://cms-uat.nhsd.io:8080/cms
      hst:defaultport: 8080
