---
definitions:
  config:
    /hst:hst/hst:hosts:
      .meta:residual-child-node-category: content
      /localhost:
        .meta:residual-child-node-category: content
        /localhost:
          .meta:residual-child-node-category: content
          /hst:root:
            .meta:residual-child-node-category: content
            hst:contextpath: ''
            hst:homepage: root
            hst:mountpoint: /hst:hst/hst:sites/common
            jcr:primaryType: hst:mount
          hst:scheme: http
          jcr:primaryType: hst:virtualhost
        hst:cmslocation: http://localhost:8080/cms
        hst:defaultport: 8080
        jcr:primaryType: hst:virtualhostgroup
      hst:diagnosticsenabled: false
