---
definitions:
  config:
    /hst:hst/hst:hosts:
      /dev-localhost:
        /localhost:
          /hst:root:
            /api:
              .meta:residual-child-node-category: content
              hst:alias: api
              hst:ismapped: false
              hst:namedpipeline: RestApiPipeline
              hst:types:
              - rest
              jcr:primaryType: hst:mount
            /gdpr:
              .meta:residual-child-node-category: content
              hst:ismapped: false
              hst:namedpipeline: TargetingRestApiPipeline
              hst:types:
              - rest
              jcr:primaryType: hst:mount
            /intranet:
              hst:mountpoint: /hst:hst/hst:sites/intranet
              jcr:primaryType: hst:mount
            /restapi:
              hst:alias: restapi
              hst:ismapped: false
              hst:namedpipeline: JaxrsRestPlainPipeline
              hst:types:
              - rest
              jcr:primaryType: hst:mount
            hst:cacheable: false
            hst:homepage: root
            hst:mountpoint: /hst:hst/hst:sites/common
            jcr:primaryType: hst:mount
          hst:scheme: http
          hst:showcontextpath: true
          hst:showport: true
          jcr:primaryType: hst:virtualhost
        hst:defaultport: 8080
        jcr:primaryType: hst:virtualhostgroup
      hst:diagnosticsenabled: false
      hst:diagnosticsthresholdmillisec: 1000
      hst:diagnosticsunitthresholdmillisec: 5
      hst:homepage: root
      hst:scheme: https
      hst:showcontextpath: false
      hst:showport: false
