<#include "../include/imports.ftlh">

<@hst.setBundle basename="essentials.global"/>
<div>
  <@hst.include ref="container"/>
</div>
<hr/>
<div class="text-center">
  <sub><@fmt.message key="footer.text" var="footer"/>${footer}</sub>
</div>


Have a question? Call us on 0300 303 5678 or contact enquiries@nhsdigital.nhs.uk.
Tell us what you think of the new website beta.
Accessibility help

Privacy and cookies

Terms and conditions
© 2017 NHS Digital

Follow us:
Twitter

Icon for LinkedIn
