name: 'Built Cache'
description: 'Asks Github to cache the .m2 and .npm folders'

runs:
  using: composite
  steps:

    - name: Get cache key helper values
      uses: actions/github-script@v6
      id: cache-key-helper
      with:
        result-encoding: string
        script: |
          return JSON.stringify({
            "year" : new Date().getFullYear(),
            "rotation" : new Date().getTimezoneOffset()
          })

    - name: Setup cache (Maven packages)
      uses: actions/cache@v3
      env:
        YEAR: ${{ fromJSON(steps.cache-key-helper.outputs.result).year }}
        ROTATION: ${{ fromJSON(steps.cache-key-helper.outputs.result).rotation }}
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-nhs-digital-${{ env.YEAR }}-${{ env.ROTATION }}

    - name: Setup cache (Node.js packages)
      uses: actions/cache@v3
      env:
        YEAR: ${{ fromJSON(steps.cache-key-helper.outputs.result).year }}
        ROTATION: ${{ fromJSON(steps.cache-key-helper.outputs.result).rotation }}
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-nhs-digital-${{ env.YEAR }}-${{ env.ROTATION }}