package uk.nhs.digital.website.beans;

import org.hippoecm.hst.content.beans.Node;
import org.hippoecm.hst.content.beans.standard.HippoHtml;
import org.onehippo.cms7.essentials.dashboard.annotations.HippoEssentialsGenerated;
import uk.nhs.digital.indices.StickySection;

@HippoEssentialsGenerated(internalName = "website:section")
@Node(jcrType = "website:section")
public class Section extends BaseCompound implements StickySection {
    @HippoEssentialsGenerated(internalName = "website:title")
    public String getTitle() {
        return getProperty("website:title");
    }

    @Override
    public String getHeading() {
        return this.getTitle();
    }

    @Override
    @HippoEssentialsGenerated(internalName = "website:headinglevel", allowModifications = false)
    public String getHeadingLevel() {
        return getProperty("website:headinglevel");
    }

    @HippoEssentialsGenerated(internalName = "website:type")
    public String getType() {
        return getProperty("website:type");
    }

    // Overridden autogenerated version to avoid issues course by getProperty return null
    @HippoEssentialsGenerated(internalName = "website:numberedList", allowModifications = false)
    public boolean getIsNumberedList() {
        Boolean result = getProperty("website:numberedList");
        return result != null && result;
    }

    @HippoEssentialsGenerated(internalName = "website:html")
    public HippoHtml getHtml() {
        return getHippoHtml("website:html");
    }

    public String getSectionType() {
        return "website-section";
    }

    public boolean isMainHeading() {
        return this.getHeadingLevel() == null || mainHeading();
    }

    private boolean mainHeading() {
        return this.getHeadingLevel().equalsIgnoreCase("Main heading")
            && this.getHeading() != null
            && !this.getHeading().isEmpty();
    }
}
