---
definitions:
  config:
    /hst:hst/hst:hosts/dev:
      /cloud:
        /bloomreach:
          /nhsdigital:
            /development:
              /content:
                .meta:residual-child-node-category: content
                jcr:primaryType: hst:virtualhost
              /hst:root:
                /gdpr:
                  hst:ismapped: false
                  hst:namedpipeline: TargetingRestApiPipeline
                  hst:types:
                  - rest
                  jcr:primaryType: hst:mount
                /restapi:
                  hst:alias: restapi
                  hst:ismapped: false
                  hst:namedpipeline: JaxrsRestPlainPipeline
                  hst:responseheaders:
                  - 'Access-Control-Allow-Origin: https://cms-dev.nhsd.io'
                  hst:types:
                  - rest
                  jcr:primaryType: hst:mount
                contentSearchEnabled: 'false'
                hst:cacheable: false
                hst:homepage: root
                hst:mountpoint: /hst:hst/hst:sites/common
                hst:responseheaders:
                - 'Strict-Transport-Security : max-age=31536000'
                - 'Content-Security-Policy: upgrade-insecure-requests'
                - 'Referrer-Policy: no-referrer-when-downgrade'
                - 'Feature-Policy: vibrate ''none''; microphone ''none''; camera ''none'';
                  payment ''none''; accelerometer ''none''; ambient-light-sensor ''none'';
                  magnetometer ''none''; midi ''none''; usb ''none''; wake-lock ''none'';
                  execution-while-out-of-viewport ''none''; sync-xhr ''self''; gyroscope
                  ''none''; push ''self''; speaker *;  fullscreen *'
                jcr:primaryType: hst:mount
              jcr:primaryType: hst:virtualhost
            jcr:primaryType: hst:virtualhost
          jcr:primaryType: hst:virtualhost
        jcr:primaryType: hst:virtualhost
      /io:
        /nhsd:
          /dev:
            /content:
              .meta:residual-child-node-category: content
              jcr:primaryType: hst:virtualhost
            /hst:root:
              /gdpr:
                hst:ismapped: false
                hst:namedpipeline: TargetingRestApiPipeline
                hst:types:
                - rest
                jcr:primaryType: hst:mount
              /restapi:
                hst:alias: restapi
                hst:ismapped: false
                hst:namedpipeline: JaxrsRestPlainPipeline
                hst:responseheaders:
                - 'Access-Control-Allow-Origin: https://cms-dev.nhsd.io'
                hst:types:
                - rest
                jcr:primaryType: hst:mount
              contentSearchEnabled: 'false'
              hst:cacheable: false
              hst:homepage: root
              hst:mountpoint: /hst:hst/hst:sites/common
              hst:responseheaders:
              - 'Strict-Transport-Security : max-age=31536000'
              - 'Content-Security-Policy: upgrade-insecure-requests'
              - 'Referrer-Policy: no-referrer-when-downgrade'
              - 'Feature-Policy: vibrate ''none''; microphone ''none''; camera ''none'';
                payment ''none''; accelerometer ''none''; ambient-light-sensor ''none'';
                magnetometer ''none''; midi ''none''; usb ''none''; wake-lock ''none'';
                execution-while-out-of-viewport ''none''; sync-xhr ''self''; gyroscope
                ''none''; push ''self''; speaker *;  fullscreen *'
              jcr:primaryType: hst:mount
            jcr:primaryType: hst:virtualhost
          jcr:primaryType: hst:virtualhost
        hst:cdnhost: //nhs-dev.global.ssl.fastly.net
        jcr:primaryType: hst:virtualhost
      jcr:primaryType: hst:virtualhostgroup
