---
definitions:
  config:
    /hst:hst/hst:hosts/training:
      /io:
        /nhsd:
          /training:
            /content:
              .meta:residual-child-node-category: content
              jcr:primaryType: hst:virtualhost
            /hst:root:
              /ndrs:
                .meta:residual-child-node-category: content
                hst:homepage: root
                hst:mountpoint: /hst:hst/hst:sites/ndrs
                jcr:primaryType: hst:mount
              /restapi:
                hst:alias: restapi
                hst:ismapped: false
                hst:namedpipeline: JaxrsRestPlainPipeline
                hst:responseheaders:
                - 'Access-Control-Allow-Origin: https://training.nhsd.io'
                hst:types:
                - rest
                jcr:primaryType: hst:mount
              hst:cacheable: false
              hst:homepage: root
              hst:mountpoint: /hst:hst/hst:sites/common
              hst:responseheaders:
              - 'Strict-Transport-Security : max-age=31536000'
              - 'Content-Security-Policy: upgrade-insecure-requests'
              - 'Referrer-Policy: no-referrer-when-downgrade'
              - 'Permissions-Policy: camera=(), display-capture=(), fullscreen=(),
                geolocation=(), microphone=(), publickey-credentials-get=(), web-share=()'
              - 'X-Content-Type-Options: nosniff'
              - 'X-Frame-Options: SAMEORIGIN'
              jcr:primaryType: hst:mount
            jcr:primaryType: hst:virtualhost
          jcr:primaryType: hst:virtualhost
        jcr:primaryType: hst:virtualhost
      jcr:primaryType: hst:virtualhostgroup
