---
definitions:
  config:
    /hst:hst/hst:configurations/common/hst:pages/service:
      /main:
        hst:componentclassname: uk.nhs.digital.common.components.ServiceComponent
        hst:template: service-article
        jcr:primaryType: hst:component
      hst:referencecomponent: hst:abstractpages/apppage
      jcr:primaryType: hst:component
