---
definitions:
  config:
    /hst:platform/hst:hosts/dev:
      /cloud:
        /bloomreach:
          /nhsdigital:
            /cms-development:
              /hst:root:
                hst:ismapped: false
                hst:namedpipeline: WebApplicationInvokingPipeline
                jcr:primaryType: hst:mount
              jcr:primaryType: hst:virtualhost
            jcr:primaryType: hst:virtualhost
          jcr:primaryType: hst:virtualhost
        jcr:primaryType: hst:virtualhost
      /io:
        /nhsd:
          /cms-dev:
            /hst:root:
              hst:ismapped: false
              hst:namedpipeline: WebApplicationInvokingPipeline
              jcr:primaryType: hst:mount
            jcr:primaryType: hst:virtualhost
          jcr:primaryType: hst:virtualhost
        hst:scheme: https
        hst:showcontextpath: false
        hst:showport: false
        jcr:primaryType: hst:virtualhost
      jcr:primaryType: hst:virtualhostgroup
