definitions:
  config:
    /hst:platform/hst:hosts/dev:
      jcr:primaryType: hst:virtualhostgroup
      /io:
        hst:scheme: https
        hst:showcontextpath: false
        hst:showport: false
        jcr:primaryType: hst:virtualhost
        /nhsd:
          jcr:primaryType: hst:virtualhost
          /cms-dev:
            jcr:primaryType: hst:virtualhost
            /hst:root:
              hst:ismapped: false
              hst:namedpipeline: WebApplicationInvokingPipeline
              jcr:primaryType: hst:mount
