---
definitions:
  config:
    /hippo:configuration/hippo:users/configuser:
      hipposys:active: true
      hipposys:passkey: jvm://
      hipposys:securityprovider: internal
      hipposys:system: true
      jcr:primaryType: hipposys:user
