definitions:
  config:
    /hst:hst/hst:configurations:
      /common:
        jcr:primaryType: hst:configuration
      /publicationsystem:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
