---
definitions:
  config:
    /hst:hst/hst:hosts:
      .meta:residual-child-node-category: content
      /dev:
        .meta:residual-child-node-category: content
        /io:
          .meta:residual-child-node-category: content
          /nhsd:
            .meta:residual-child-node-category: content
            /ps:
              .meta:residual-child-node-category: content
              /dev:
                .meta:residual-child-node-category: content
                /web:
                  .meta:residual-child-node-category: content
                  /hippo-delivery:
                    .meta:residual-child-node-category: content
                    /hst:root:
                      .meta:residual-child-node-category: content
                      /publications:
                        .meta:residual-child-node-category: content
                        hst:homepage: root
                        hst:mountpoint: /hst:hst/hst:sites/publicationsystem
                        jcr:primaryType: hst:mount
                      hst:alias: common-context
                      hst:contextpath: ''
                      hst:homepage: root
                      hst:mountpoint: /hst:hst/hst:sites/common
                      jcr:primaryType: hst:mount
                    jcr:primaryType: hst:virtualhost
                  jcr:primaryType: hst:virtualhost
                jcr:primaryType: hst:virtualhost
              jcr:primaryType: hst:virtualhost
            jcr:primaryType: hst:virtualhost
          hst:scheme: http
          hst:showcontextpath: false
          jcr:primaryType: hst:virtualhost
        hst:cmslocation: http://blackhole-hippo-authoring.web.dev.ps.nhsd.io/cms
        jcr:primaryType: hst:virtualhostgroup
      /dev-cms:
        .meta:residual-child-node-category: content
        /io:
          .meta:residual-child-node-category: content
          /nhsd:
            .meta:residual-child-node-category: content
            /ps:
              .meta:residual-child-node-category: content
              /dev:
                .meta:residual-child-node-category: content
                /web:
                  .meta:residual-child-node-category: content
                  /hippo-authoring:
                    .meta:residual-child-node-category: content
                    /hst:root:
                      .meta:residual-child-node-category: content
                      /publications:
                        .meta:residual-child-node-category: content
                        hst:homepage: root
                        hst:mountpoint: /hst:hst/hst:sites/publicationsystem
                        jcr:primaryType: hst:mount
                      hst:alias: common-context
                      hst:contextpath: /site
                      hst:homepage: root
                      hst:mountpoint: /hst:hst/hst:sites/common
                      hst:showcontextpath: true
                      jcr:primaryType: hst:mount
                    jcr:primaryType: hst:virtualhost
                  jcr:primaryType: hst:virtualhost
                jcr:primaryType: hst:virtualhost
              jcr:primaryType: hst:virtualhost
            jcr:primaryType: hst:virtualhost
          hst:scheme: http
          hst:showcontextpath: false
          jcr:primaryType: hst:virtualhost
        hst:cmslocation: http://hippo-authoring.web.dev.ps.nhsd.io/cms
        jcr:primaryType: hst:virtualhostgroup
      /ondemand:
        .meta:residual-child-node-category: content
        /com:
          .meta:residual-child-node-category: content
          /onehippo:
            .meta:residual-child-node-category: content
            /test:
              .meta:residual-child-node-category: content
              /nhs:
                .meta:residual-child-node-category: content
                /www:
                  .meta:residual-child-node-category: content
                  /hst:root:
                    .meta:residual-child-node-category: content
                    /publications:
                      .meta:residual-child-node-category: content
                      hst:homepage: root
                      hst:mountpoint: /hst:hst/hst:sites/publicationsystem
                      jcr:primaryType: hst:mount
                    hst:alias: common-context
                    hst:contextpath: /site
                    hst:homepage: root
                    hst:mountpoint: /hst:hst/hst:sites/common
                    hst:showcontextpath: false
                    jcr:primaryType: hst:mount
                  jcr:primaryType: hst:virtualhost
                jcr:primaryType: hst:virtualhost
              jcr:primaryType: hst:virtualhost
            jcr:primaryType: hst:virtualhost
          jcr:primaryType: hst:virtualhost
        hst:cmslocation: https://blackhole-cms-nhs.test.onehippo.com
        jcr:primaryType: hst:virtualhostgroup
      /ondemand-cms:
        .meta:residual-child-node-category: content
        /com:
          .meta:residual-child-node-category: content
          /onehippo:
            .meta:residual-child-node-category: content
            /test:
              .meta:residual-child-node-category: content
              /cms-nhs:
                .meta:residual-child-node-category: content
                /hst:root:
                  .meta:residual-child-node-category: content
                  /publications:
                    .meta:residual-child-node-category: content
                    hst:homepage: root
                    hst:mountpoint: /hst:hst/hst:sites/publicationsystem
                    jcr:primaryType: hst:mount
                  hst:alias: common-context
                  hst:contextpath: /site
                  hst:homepage: root
                  hst:mountpoint: /hst:hst/hst:sites/common
                  hst:showcontextpath: false
                  jcr:primaryType: hst:mount
                jcr:primaryType: hst:virtualhost
              jcr:primaryType: hst:virtualhost
            jcr:primaryType: hst:virtualhost
          jcr:primaryType: hst:virtualhost
        hst:cmslocation: https://cms-nhs.test.onehippo.com
        jcr:primaryType: hst:virtualhostgroup
      hst:scheme: https
      jcr:primaryType: hst:virtualhosts
