definitions:
  config:
    /hst:hst/hst:hosts:
      .meta:residual-child-node-category: content
      jcr:primaryType: hst:virtualhosts
      # this deploys "site" as root application
      hst:defaultcontextpath: ""

      # locahost
      /localhost:
        .meta:residual-child-node-category: content
        jcr:primaryType: hst:virtualhostgroup
        hst:cmslocation: http://localhost:8080/cms
        hst:defaultport: 8080
        /localhost:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:virtualhost
          /hst:root:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:mount
            hst:homepage: root
            hst:mountpoint: /hst:hst/hst:sites/common
            /publications:
              .meta:residual-child-node-category: content
              jcr:primaryType: hst:mount
              hst:homepage: root
              hst:mountpoint: /hst:hst/hst:sites/publicationsystem

      # For local testing in Vagrant
      /vagrant:
        .meta:residual-child-node-category: content
        jcr:primaryType: hst:virtualhostgroup
        hst:cmslocation: http://hippo-authoring.int:8080/cms
        hst:defaultport: 8080
        /int:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:virtualhost
          hst:showcontextpath: false
          /hippo-delivery:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:virtualhost
            /hst:root:
              .meta:residual-child-node-category: content
              jcr:primaryType: hst:mount
              hst:homepage: root
              hst:mountpoint: /hst:hst/hst:sites/common
              /publications:
                .meta:residual-child-node-category: content
                jcr:primaryType: hst:mount
                hst:homepage: root
                hst:mountpoint: /hst:hst/hst:sites/publicationsystem

      /dev:
        .meta:residual-child-node-category: content
        jcr:primaryType: hst:virtualhostgroup
        hst:cmslocation: http://hippo-authoring.dev.ps.digital.nhsd.uk/cms
        hst:defaultport: 8080
        /uk:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:virtualhost
          hst:showcontextpath: false
          /nhs:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:virtualhost
            /digital:
              .meta:residual-child-node-category: content
              jcr:primaryType: hst:virtualhost
              /ps:
                .meta:residual-child-node-category: content
                jcr:primaryType: hst:virtualhost
                /dev:
                  .meta:residual-child-node-category: content
                  jcr:primaryType: hst:virtualhost
                  /hippo-delivery:
                    .meta:residual-child-node-category: content
                    jcr:primaryType: hst:virtualhost
                    /hst:root:
                      .meta:residual-child-node-category: content
                      jcr:primaryType: hst:mount
                      hst:homepage: root
                      hst:mountpoint: /hst:hst/hst:sites/common
                      /publications:
                        .meta:residual-child-node-category: content
                        jcr:primaryType: hst:mount
                        hst:homepage: root
                        hst:mountpoint: /hst:hst/hst:sites/publicationsystem
