---
definitions:
  config:
    /hst:hst/hst:hosts:
      .meta:residual-child-node-category: content
      /dev:
        .meta:residual-child-node-category: content
        /io:
          .meta:residual-child-node-category: content
          /nhsd:
            .meta:residual-child-node-category: content
            /ps:
              .meta:residual-child-node-category: content
              /dev:
                .meta:residual-child-node-category: content
                /web:
                  .meta:residual-child-node-category: content
                  /hippo-delivery:
                    .meta:residual-child-node-category: content
                    /hst:root:
                      .meta:residual-child-node-category: content
                      /publications:
                        .meta:residual-child-node-category: content
                        hst:homepage: root
                        hst:mountpoint: /hst:hst/hst:sites/publicationsystem
                        jcr:primaryType: hst:mount
                      hst:alias: common-context
                      hst:homepage: root
                      hst:mountpoint: /hst:hst/hst:sites/common
                      jcr:primaryType: hst:mount
                    jcr:primaryType: hst:virtualhost
                  jcr:primaryType: hst:virtualhost
                jcr:primaryType: hst:virtualhost
              jcr:primaryType: hst:virtualhost
            jcr:primaryType: hst:virtualhost
          hst:showcontextpath: false
          jcr:primaryType: hst:virtualhost
        hst:cmslocation: http://hippo-authoring.dev.ps.digital.nhsd.uk/cms
        hst:defaultport: 8080
        jcr:primaryType: hst:virtualhostgroup
      /localhost:
        .meta:residual-child-node-category: content
        /localhost:
          .meta:residual-child-node-category: content
          /hst:root:
            .meta:residual-child-node-category: content
            /publications:
              .meta:residual-child-node-category: content
              hst:homepage: root
              hst:mountpoint: /hst:hst/hst:sites/publicationsystem
              jcr:primaryType: hst:mount
            hst:alias: common-context
            hst:homepage: root
            hst:mountpoint: /hst:hst/hst:sites/common
            jcr:primaryType: hst:mount
          jcr:primaryType: hst:virtualhost
        hst:cmslocation: http://localhost:8080/cms
        hst:defaultport: 8080
        jcr:primaryType: hst:virtualhostgroup
      /ondemand:
        .meta:residual-child-node-category: content
        /com:
          .meta:residual-child-node-category: content
          /onehippo:
            .meta:residual-child-node-category: content
            /test:
              .meta:residual-child-node-category: content
              /nhs:
                .meta:residual-child-node-category: content
                /www:
                  .meta:residual-child-node-category: content
                  /hst:root:
                    .meta:residual-child-node-category: content
                    /publications:
                      .meta:residual-child-node-category: content
                      hst:homepage: root
                      hst:mountpoint: /hst:hst/hst:sites/publicationsystem
                      jcr:primaryType: hst:mount
                    hst:alias: common-context
                    hst:contextpath: /site
                    hst:homepage: root
                    hst:mountpoint: /hst:hst/hst:sites/common
                    hst:showcontextpath: false
                    jcr:primaryType: hst:mount
                  jcr:primaryType: hst:virtualhost
                jcr:primaryType: hst:virtualhost
              jcr:primaryType: hst:virtualhost
            jcr:primaryType: hst:virtualhost
          jcr:primaryType: hst:virtualhost
        hst:cmslocation: https://cms-nhs.test.onehippo.com/?0
        hst:defaultport: 8080
        jcr:primaryType: hst:virtualhostgroup
      /vagrant:
        .meta:residual-child-node-category: content
        /int:
          .meta:residual-child-node-category: content
          /hippo-delivery:
            .meta:residual-child-node-category: content
            /hst:root:
              .meta:residual-child-node-category: content
              /publications:
                .meta:residual-child-node-category: content
                hst:homepage: root
                hst:mountpoint: /hst:hst/hst:sites/publicationsystem
                jcr:primaryType: hst:mount
              hst:alias: common-context
              hst:homepage: root
              hst:mountpoint: /hst:hst/hst:sites/common
              jcr:primaryType: hst:mount
            jcr:primaryType: hst:virtualhost
          hst:showcontextpath: false
          jcr:primaryType: hst:virtualhost
        hst:cmslocation: http://hippo-authoring.int:8080/cms
        hst:defaultport: 8080
        jcr:primaryType: hst:virtualhostgroup
      hst:defaultcontextpath: ''
      jcr:primaryType: hst:virtualhosts
