---
definitions:
  config:
    /hst:hst/hst:hosts:
      .meta:residual-child-node-category: content
      /prd:
        /uk:
          /nhs:
            /digital:
              /beta:
                /hst:root:
                  hst:contextpath: /site
                  hst:homepage: root
                  hst:mountpoint: /hst:hst/hst:sites/common
                  hst:showcontextpath: false
                  jcr:primaryType: hst:mount
                jcr:primaryType: hst:virtualhost
              /cms:
                /hst:root:
                  hst:contextpath: /site
                  hst:homepage: root
                  hst:mountpoint: /hst:hst/hst:sites/common
                  hst:showcontextpath: false
                  jcr:primaryType: hst:mount
                jcr:primaryType: hst:virtualhost
              jcr:primaryType: hst:virtualhost
            jcr:primaryType: hst:virtualhost
          jcr:primaryType: hst:virtualhost
        hst:cmslocation: https://cms.digital.nhs.uk
        jcr:primaryType: hst:virtualhostgroup
      /tst:
        /io:
          /nhsd:
            /cms-tst:
              /hst:root:
                hst:contextpath: /site
                hst:homepage: root
                hst:mountpoint: /hst:hst/hst:sites/common
                hst:showcontextpath: false
                jcr:primaryType: hst:mount
              jcr:primaryType: hst:virtualhost
            /tst:
              /hst:root:
                hst:contextpath: /site
                hst:homepage: root
                hst:mountpoint: /hst:hst/hst:sites/common
                hst:showcontextpath: false
                jcr:primaryType: hst:mount
              jcr:primaryType: hst:virtualhost
            jcr:primaryType: hst:virtualhost
          jcr:primaryType: hst:virtualhost
        hst:cmslocation: https://cms-tst.nhsd.io
        jcr:primaryType: hst:virtualhostgroup
      /uat:
        /io:
          /nhsd:
            /cms-uat:
              /hst:root:
                hst:contextpath: /site
                hst:homepage: root
                hst:mountpoint: /hst:hst/hst:sites/common
                hst:showcontextpath: false
                jcr:primaryType: hst:mount
              jcr:primaryType: hst:virtualhost
            /uat:
              /hst:root:
                hst:contextpath: /site
                hst:homepage: root
                hst:mountpoint: /hst:hst/hst:sites/common
                hst:showcontextpath: false
                jcr:primaryType: hst:mount
              jcr:primaryType: hst:virtualhost
            jcr:primaryType: hst:virtualhost
          jcr:primaryType: hst:virtualhost
        hst:cmslocation: https://cms-uat.nhsd.io
        jcr:primaryType: hst:virtualhostgroup
      hst:scheme: https
