definitions:
  config:
    /hst:hst/hst:hosts:
      .meta:residual-child-node-category: content
      jcr:primaryType: hst:virtualhosts
      hst:defaultcontextpath: /site
      /dev-localhost:
        .meta:residual-child-node-category: content
        jcr:primaryType: hst:virtualhostgroup
        hst:cmslocation: http://localhost:8080/cms
        hst:defaultport: 8080
        /localhost:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:virtualhost
          /hst:root:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:mount
            hst:homepage: root
            hst:mountpoint: /hst:hst/hst:sites/publicationsystem
