name: Convert new PRs to draft

on:
  pull_request:
    types: [opened]

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Convert to draft
        run: |
          gh pr ready ${context.payload.pull_request.number} --undo
