# Prepare the git tags for the next stage of deploying to production
# and report what will be deployed.
name: Deploy to Production - Stage 1

on:
  schedule:
    # Runs at 4pm BST weekdays
    - cron: "0 15 * * 1-5"

env:
  SLACK_CHANNEL: "C0353KHFXNJ"

jobs:

  prepare-prod-deployment:
    name: Prepare Tags
    runs-on: ubuntu-latest
    timeout-minutes: 85

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need all the tags for versioning
          ref: master

      # If this fails on GitHub for a permissions issues (that may seem unrelated) run the failing command
      # on your DevOps laptop. Then rerun the failed job.
      - name: Move the RC Tag
        run: |
          make git.update-environment-tag ENV=prd VERSION=rc
          make git.update-environment-tag ENV=rc VERSION=uat

      - name: Get JIRA List
        id: getJiraListId
        run: |
          git log --format="* %s. [Author %an]" uat..rc
          jiraList=$(echo $(git log --format="\n %s. [Author %an]" prd..rc))
          echo "jiraListIds=${jiraList}" >> $GITHUB_OUTPUT

      #
      # Send a Slack Message to
      #
      - name: Slack message (List Jira Tickets to be released)
        if: ${{ success() }}
        uses: ./.github/actions/slack-message
        with:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
          SLACK_CHANNEL: ${{ env.SLACK_CHANNEL }}
          TITLE: ":clock1: Scheduled Deploying to Production"
          MESSAGE: |
            Release to production has been scheduled at 12:05 on the next working day. The following new changes (if any) will be released: ${{steps.getJiraListId.outputs.jiraListIds}}

      - name: Slack message (Job failed message)
        if: ${{ failure() }}
        uses: ./.github/actions/slack-message
        with:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
          SLACK_CHANNEL: ${{ env.SLACK_CHANNEL }}
          TITLE: ":alarm_clock: Error Message"
          MESSAGE: |
            Failed to schedule a release to production. Please check the logs for more details.