name: Pull Request Workflow

on:
  push:
    branches:
      - playwright

jobs:
  build-and-test:
    name: "Build and test project"
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      HIPPO_MAVEN_PASSWORD: ${{ secrets.HIPPO_MAVEN_PASSWORD }}
      HIPPO_MAVEN_USERNAME: ${{ secrets.HIPPO_MAVEN_USERNAME }}

    steps:

      # Step 1
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Step 2
      - name: Check commit message
        run: make check.commit-msg

      # Step 3
      - name: Print Google Chrome version
        run: google-chrome --version

      # Step 4
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8

      # Step 5
      - name: Get cache key helper values
        uses: actions/github-script@v4.0.2
        id: cache-key-helper
        with:
          result-encoding: string
          script: |
            return JSON.stringify({
              "year" : new Date().getFullYear(),
              "rotation" : new Date().getTimezoneOffset()
            })

      - name: Setup cache (Maven packages)
        uses: actions/cache@v2
        env:
          YEAR: ${{ fromJSON(steps.cache-key-helper.outputs.result).year }}
          ROTATION: ${{ fromJSON(steps.cache-key-helper.outputs.result).rotation }}
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-nhs-digital-${{ env.YEAR }}-${{ env.ROTATION }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-nhs-digital-${{ env.YEAR }}-${{ env.ROTATION }}-
            ${{ runner.os }}-maven-nhs-digital-${{ env.YEAR }}-
            ${{ runner.os }}-maven-nhs-digital-
            ${{ runner.os }}-maven-nhs-

      - name: Setup cache (Node.js packages)
        uses: actions/cache@v2
        env:
          YEAR: ${{ fromJSON(steps.cache-key-helper.outputs.result).year }}
          ROTATION: ${{ fromJSON(steps.cache-key-helper.outputs.result).rotation }}
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-nhs-digital-${{ env.YEAR }}-${{ env.ROTATION }}
          restore-keys: |
            ${{ runner.os }}-node-nhs-digital-${{ env.YEAR }}-
            ${{ runner.os }}-node-nhs-digital-
            ${{ runner.os }}-node-nhs-

      # Step 6
      - name: Check YAML formatting
        run: make check.yaml

      # Step 7
      - name: Test Project
        run: make test.playwright

      #
      # Step 8
      # Store test results as an artifact
      #
      - name: "Upload test result artifacts on failure"
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: playwright-report
          path: |
            acceptance-tests/src/test/node/playwright-report/

      - name: "Upload test result artifacts on success"
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: playwright-report
          path: |
            acceptance-tests/src/test/node/playwright-report/
