name: Pull Request QA Approval

on:
  issue_comment:
    types: [ created ]

jobs:
  testing:
    name: Check acction starts
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: echo "Hello"
