
name: Remove Old Configuration Files

on:
  schedule:
    - cron: "0 9 * * 1-5"

jobs:
  remove-old-configuration:
    name: Remove Old Configuration Files
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Get API access token and verify it.
      - name: Get BR Cloud Token
        id: jwt_token
        uses: ./.github/actions/br-cloud-token
        with:
          MISSION_CONTROL_API_USERNAME: ${{ secrets.MISSION_CONTROL_API_USERNAME }}
          MISSION_CONTROL_API_PASSWORD: ${{ secrets.MISSION_CONTROL_API_PASSWORD }}
          MISSION_CONTROL_API_HOST: ${{ vars.BR_CLOUD }}

      - name: Get All Configuration Files
        id: all-config-file-ids
        run: |
          response=$(curl \
          -H "Authorization: Bearer ${{ steps.jwt_token.outputs.token1 }}" \
          -X GET https://api.${{ vars.BR_CLOUD }}/v3/appconfigfiles)
          echo "allConfigFiles=${response}" >> $GITHUB_OUTPUT

      - name: Get All Environment
        id: all-envs
        run: |
          response=$(curl \
          -H "Authorization: Bearer ${{ steps.jwt_token.outputs.token1 }}" \
          -X GET https://api.${{ vars.BR_CLOUD }}/v3/environments)
          availEnvs=$(echo ${response} | jq --compact-output '[.items[] | {name: .name}] | map(select(.name )) | map(.name)')
          echo "allEnvs=${availEnvs}" >> $GITHUB_OUTPUT
          echo "Avialable Envs are " ${availEnvs}

      - name: Remove Old System & AWS Files
        run: |
          declare -a  envList=$(echo  '${{steps.all-envs.outputs.allEnvs}}' | tr "[" "(" | tr "]" ")" | tr "," " ")
          for value in "${envList[@]}"
          do
            declare -a  envSysConfigIds=$(echo '${{steps.all-config-file-ids.outputs.allConfigFiles}}' |  jq --compact-output '[.[] | {id: .id , date: .createdAt, name: .name}] | sort_by(.date) | reverse| map(select(.name | test("'${value}'-system"))) | map(.id)| .[3:] ' | tr "[" "(" | tr "]" ")" | tr "," " " )
            declare -a  envAWSConfigIds=$(echo '${{steps.all-config-file-ids.outputs.allConfigFiles}}' |  jq --compact-output '[.[] | {id: .id , date: .createdAt, name: .name}] | sort_by(.date) | reverse| map(select(.name | test("'${value}'-aws"))) | map(.id) | .[3:]' | tr "[" "(" | tr "]" ")" | tr "," " " )

            for i in "${!envSysConfigIds[@]}";
            do
              printf "%s\t%s\n" "$i" "${envSysConfigIds[$i]}"
              response=$(curl \
                -H "Authorization: Bearer ${{ steps.jwt_token.outputs.token1 }}" \
                -X DELETE https://api.${{ vars.BR_CLOUD }}/v3/appconfigfiles/${envSysConfigIds[$i]})
              echo ${response}
            done

            for i in "${!envAWSConfigIds[@]}";
            do
              printf "%s\t%s\n" "$i" "${envAWSConfigIds[$i]}"
              response=$(curl \
                -H "Authorization: Bearer ${{ steps.jwt_token.outputs.token1 }}" \
                -X DELETE https://api.${{ vars.BR_CLOUD }}/v3/appconfigfiles/${envAWSConfigIds[$i]})
              echo ${response}

            done
          done

      - name: Remove old hippo filter files
        run: |
            declare -a  envHippoConfigIds=$(echo '${{steps.all-config-file-ids.outputs.allConfigFiles}}' |  jq --compact-output '[.[] | {id: .id , date: .createdAt, name: .name}] | sort_by(.date) | reverse| map(select(.name | test("hippo-"))) | map(.id)| .[3:] ' | tr "[" "(" | tr "]" ")" | tr "," " " )
            for i in "${!envHippoConfigIds[@]}";
            do
              printf "%s\t%s\n" "$i" "${envHippoConfigIds[$i]}"
              response=$(curl \
                -H "Authorization: Bearer ${{ steps.jwt_token.outputs.token1 }}" \
                -X DELETE https://api.${{ vars.BR_CLOUD }}/v3/appconfigfiles/${envHippoConfigIds[$i]})
              echo ${response}
            done